# Generated by Django 5.0.7 on 2024-09-09 02:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Blog_App", "0002_database_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="database",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name="database",
            name="image",
            field=models.ImageField(null=True, upload_to="image_folder"),
        ),
    ]
