# Generated by Django 5.0.7 on 2024-09-09 02:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Blog_App", "0003_database_slug_alter_database_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="database",
            name="slug",
            field=models.SlugField(blank=True),
        ),
    ]
